env: flex
runtime: nodejs

env_variables:
  SQL_USER: salat
  SQL_PASSWORD: dambldor
  SQL_DATABASE: tourism
  INSTANCE_CONNECTION_NAME: my-project-1474294752715:us-central1:mysqlconnection

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: my-project-1474294752715:us-central1:mysqlconnection
# [END cloudsql_settings]
# [END app_yaml]
